package seedu.address.testutil;

/**
 * A utility class containing a list of {@code String} objects to be used in tests.
 */
public class TypicalStatistics {

    public static final String BLANKTABLEHTMLSTATS = "<table style=\"width:100%\">\n"
            + "  <tr>\n"
            + "    <th>Categories</th>\n"
            + "    <th>Amount Spent ($)</th>\n"
            + "    <th>Entry Counts</th>\n"
            + "    <th>Percentage (%)</th>\n"
            + "  </tr>\n"
            + "</table>";

    public static final String BLANKTABLEHTMLCOMPARE = "<table style=\"width:100%\">\n"
            + "  <tr>\n"
            + "    <th>Categories</th>\n"
            + "    <th>Amount Spent ($)</th>\n"
            + "    <th>Entry Counts</th>\n"
            + "    <th>Percentage (%)</th>\n"
            + "  </tr>\n"
            + "</table>";


    public static final String EMPTYTABLEHTMLTREND = "<br>Amount Spent ($): <br><table style=\"width:100%\">\n"
            + "  <tr>\n"
            + "    <th>Period Starting (M) : till End</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>FOOD</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>TRANSPORT</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>SHOPPING</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>WORK</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>UTILITIES</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>HEALTHCARE</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>ENTERTAINMENT</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>TRAVEL</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>OTHERS</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>ALL</th>\n"
            + "  </tr>\n"
            + "</table><br>Counts: <br><table style=\"width:100%\">\n"
            + "  <tr>\n"
            + "    <th>Period Starting (M) : till End</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>FOOD</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>TRANSPORT</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>SHOPPING</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>WORK</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>UTILITIES</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>HEALTHCARE</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>ENTERTAINMENT</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>TRAVEL</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>OTHERS</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>ALL</th>\n"
            + "  </tr>\n"
            + "</table>";

    public static final String DUCKRICETABLEHTMLSTATS =
            "<table style=\"width:100%\">\n"
            + "  <tr>\n"
            + "    <th>Categories</th>\n"
            + "    <th>Amount Spent ($)</th>\n"
            + "    <th>Entry Counts</th>\n"
            + "    <th>Percentage (%)</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>FOOD</th>\n"
            + "    <th>3.00</th>\n"
            + "    <th>1</th>\n"
            + "    <th>100.00</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>ALL</th>\n"
            + "    <th>3.00</th>\n"
            + "    <th>1</th>\n"
            + "    <th>100.00</th>\n"
            + "  </tr>\n"
            + "</table>";

    public static final String DUCKRICETABLEHTMLCOMPARE =
            "<table style=\"width:100%\">\n"
            + "  <tr>\n"
            + "    <th>Categories</th>\n"
            + "    <th>Amount Spent ($)</th>\n"
            + "    <th>Entry Counts</th>\n"
            + "    <th>Percentage (%)</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>FOOD</th>\n"
            + "    <th>3.00</th>\n"
            + "    <th>1</th>\n"
            + "    <th>100.00</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>ALL</th>\n"
            + "    <th>3.00</th>\n"
            + "    <th>1</th>\n"
            + "    <th>100.00</th>\n"
            + "  </tr>\n"
            + "</table>";

    public static final String DUCKRICETABLEHTMLTREND =
            "<br>Amount Spent ($): <br><table style=\"width:100%\">\n"
            + "  <tr>\n"
            + "    <th>Period Starting (M) :</th>\n"
            + "    <th>01-01-2019 till End</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>FOOD</th>\n"
            + "    <th>3.00</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>TRANSPORT</th>\n"
            + "    <th>0.00</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>SHOPPING</th>\n"
            + "    <th>0.00</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>WORK</th>\n"
            + "    <th>0.00</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>UTILITIES</th>\n"
            + "    <th>0.00</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>HEALTHCARE</th>\n"
            + "    <th>0.00</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>ENTERTAINMENT</th>\n"
            + "    <th>0.00</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>TRAVEL</th>\n"
            + "    <th>0.00</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>OTHERS</th>\n"
            + "    <th>0.00</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>ALL</th>\n"
            + "    <th>3.00</th>\n"
            + "  </tr>\n"
            + "</table><br>Counts: <br><table style=\"width:100%\">\n"
            + "  <tr>\n"
            + "    <th>Period Starting (M) :</th>\n"
            + "    <th>01-01-2019 till End</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>FOOD</th>\n"
            + "    <th>1</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>TRANSPORT</th>\n"
            + "    <th>0</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>SHOPPING</th>\n"
            + "    <th>0</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>WORK</th>\n"
            + "    <th>0</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>UTILITIES</th>\n"
            + "    <th>0</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>HEALTHCARE</th>\n"
            + "    <th>0</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>ENTERTAINMENT</th>\n"
            + "    <th>0</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>TRAVEL</th>\n"
            + "    <th>0</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>OTHERS</th>\n"
            + "    <th>0</th>\n"
            + "  </tr>\n"
            + "  <tr>\n"
            + "    <th>ALL</th>\n"
            + "    <th>1</th>\n"
            + "  </tr>\n"
            + "</table>";
}
